### PR TITLE
fix: auto approve action failed (#1)

### PR DESCRIPTION
**Pull request by SaarChaffee**

### CODE REVIEW

**Comment by MaikoTan** [comment]
草

**Review by MaikoTan — APPROVED** [review]
草

**Comment by SaarChaffee** [comment]
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by MaikoTan** [comment]
You have permission now!

**Comment by SaarChaffee** [comment]
> You have permission now!

No, I don't.

**Comment by MaikoTan** [comment]
> > You have permission now!
> 
> No, I don't.

Check again?

**Pull request merged**
